### ISSUE TITLE
Panic attempting to print schema

### ISSUE THREAD

**Issue by nonspecialist** [fraugster/parquet-go#12]
When using `examples/read-low-level/main.go` (which is very similar to the `parquet-tool -cmd schema` functionality) I get panics no matter what parquet file I point it at. These files are all readable perfectly well by pyspark.

Example stack trace, where `main.go` is a direct copy from the example code:

```
goroutine 1 [running]:
github.com/fraugster/parquet-go.(*schema).GetSchemaDefinition(0xc00002c300, 0x10)
	/home/cmp/Build/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/schema.go:936 +0x7d
main.printFile(0x7ffd484627d7, 0x2f, 0x0, 0x0)
	/home/abc/Build/dump-go/main.go:40 +0x193
main.main()
	/home/abc/Build/dump-go/main.go:21 +0x168
``` 

I'll attach an example of a parquet file that makes things go boom ...

**Comment by nonspecialist** [comment]
Attached example zip of a parquet that go :boom: 

[issue.zip](https://github.com/fraugster/parquet-go/files/5733302/issue.zip)

**Comment by fzerorubigd** [comment]
I checked and this is the schema 
```
message schema {
  optional binary Op (UTF8);
  required binary TIMESTAMP (UTF8);
  optional binary itf_processed_ind (UTF8);
  optional binary itf_refresh_ind (UTF8);
  optional fixed_len_byte_array(5) itf_record_id (DECIMAL);
  optional binary itf_action_ind (UTF8);
  optional binary itf_summarised_ind (UTF8);
  optional binary itf_change_level (UTF8);
  optional int64 itf_create_tms (TIMESTAMP_MICROS);
  optional int64 itf_processed_tms (TIMESTAMP_MICROS);
  optional int32 sku;
  optional binary barcode (UTF8);
  optional int64 start_date (TIMESTAMP_MICROS);
  optional int64 end_date (TIMESTAMP_MICROS);
  optional int32 pce_type (INT_8);
  optional int32 pce_id;
  optional binary pce_desc (UTF8);
  optional int32 pce_reason (INT_8);
  optional binary pce_status (UTF8);
  optional binary clearance_ind (UTF8);
  optional int32 markdown_type (INT_8);
  optional int32 website (INT_8);
  optional fixed_len_byte_array(9) price (DECIMAL);
  optional fixed_len_byte_array(9) cost (DECIMAL);
  optional fixed_len_byte_array(9) saleprice (DECIMAL);
  optional int32 display_state (INT_8);
  optional fixed_len_byte_array(9) taxrate (DECIMAL);
  optional int64 future_extract_date (TIMESTAMP_MICROS);
  optional fixed_len_byte_array(5) screen_display (DECIMAL);
}
```

Is it correct to have a fixed-length byte array with DECIMAL logical type? we have this ```optional fixed_len_byte_array(5) itf_record_id (DECIMAL);```

/cc @akrennmair

**Comment by akrennmair** [comment]
I looked into this more closely, and it came from our parser not handling the _converted_ type `DECIMAL` properly, and assuming that `DECIMAL` would always have to be parsed as _logical_ type with non-optional scale and precision fields. I fixed this in the latest commit, so the fix will be available in the next release.
