### ISSUE TITLE
FileWriter sets TotalByteSize to 0

### ISSUE THREAD

**Issue by c-childs** [fraugster/parquet-go#16]
When using the `FileWriter`, the generated row group metadata sometimes has a  `TotalByteSize` of 0 even though the row group contains multiple column chunks.  After looking through the code, it appears that the `TotalByteSize` is set to 0 in `FlushRowGroup(…)` here: 
```
fw.rowGroups = append(fw.rowGroups, &parquet.RowGroup{
	Columns:        cc,
	TotalByteSize:  0,
	NumRows:        fw.rowGroupNumRecords(),
	SortingColumns: nil,
})
```
Is there a specific reason the `TotalByteSize` is being set to 0?

If not, could one possible solution be to set the `TotalByteSize` to the sum of each column chunk's `TotalCompressedSize` for an accurate estimation of the size?

**Comment by fzerorubigd** [comment]
Based on documents ```TotalByteSize: Total byte size of all the uncompressed column data in this row group *``` 
Also, we keep track of the uncompressed size of each chunk in column chunk metadata. (ColumnChunk.MetaData.TotalUncompressedSize) the size for each chunk contains header size as well, so we can put the sum in TotalByteSize. 
I need to confirm this with a valid parquet file generated by the Java version. if you have a sample please share, if not for me it takes a lot of effort to create the sample (I am no longer working with the Parquet files)

**Comment by c-childs** [comment]
Okay sounds good - here's a valid parquet file for testing: [parquet_test_file.zip](https://github.com/fraugster/parquet-go/files/5928570/parquet_test_file.zip)

**Comment by c-childs** [comment]
Hey @fzerorubigd, is there a time estimate on when this will be fixed?
