### ISSUE TITLE
Memory issues when reading files with large row groups

### ISSUE THREAD

**Issue by andrey-klochkov-liftoff** [fraugster/parquet-go#21]
I tried using the low level reader to read a ~300MB file with large number of columns, with the data that is very sparse (most of columns are nulls), and the reader attempts to read the entire row group at once before producing the first record. I read the code and realized that the reader reads all data pages from all column chunks belonging to a row group into memory. Also, when reading null columns the reader actually creates values arrays with null values in every element, which makes it so much worse. 

In comparison, the Arrow C++ library and the Presto implementation of Parquet both read pages lazily as the client scans through rows, and they don't create values arrays at all for pages with nulls, and in general don't add null values to the values array.

Is there something I'm missing, or this library can't actually be used with larger sparse files?

I guess a possible workaround would be to configure the app that produces our Parquet files to create small row groups but that may have other negative consequences. The Parquet format docs recommend to set 512MB-1GB size for row groups, and I can't make this library work even with a 300MB file.

**Comment by FaridHub** [comment]
Facing the same problem of reading a 2.5 GB parquet file.

**Comment by akrennmair** [comment]
With the latest release [https://github.com/fraugster/parquet-go/releases/tag/v0.9.0](v0.9.0), we added several improvements to memory usage, in particular when reading individual pages. This should alleviate the limitations that you've faced in the past.
