### ISSUE TITLE
"not enough data to read all miniblock bit widths" when writing one record

### ISSUE THREAD

**Issue by danp** [fraugster/parquet-go#27]
I seem to have run into trouble when writing one record using `parquet.Encoding_DELTA_LENGTH_BYTE_ARRAY` or `parquet.Encoding_DELTA_BYTE_ARRAY`. Reading the written data errors with:

```
not enough data to read all miniblock bit widths: unexpected EOF
```

Here is a complete test that fails for me, using v0.3.0:

```go
func TestOne(t *testing.T) {
	var buf bytes.Buffer

	wr := goparquet.NewFileWriter(&buf)

	bas, err := goparquet.NewByteArrayStore(parquet.Encoding_DELTA_LENGTH_BYTE_ARRAY, true, &goparquet.ColumnParameters{})
	if err != nil {
		t.Fatal(err)
	}

	col := goparquet.NewDataColumn(bas, parquet.FieldRepetitionType_OPTIONAL)
	if err := wr.AddColumn("name", col); err != nil {
		t.Fatal(err)
	}

	for i := 0; i < 1; i++ {
		rec := map[string]interface{}{
			"name": []byte("dan"),
		}

		if err := wr.AddData(rec); err != nil {
			t.Fatal(err)
		}
	}

	if err := wr.Close(); err != nil {
		t.Fatal(err)
	}

	rd, err := goparquet.NewFileReader(bytes.NewReader(buf.Bytes()))
	if err != nil {
		t.Fatal(err)
	}

	for {
		row, err := rd.NextRow()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			t.Fatal(err)
		}
		t.Log(row)
	}
}
```

Changing either:
* `i < 1` to `i < 2`
* `parquet.Encoding_DELTA_LENGTH_BYTE_ARRAY` to `parquet.Encoding_PLAIN`

Gets it passing.

Hopefully I haven't misused something here.

**Comment by akrennmair** [comment]
Hi @danp! Sorry for not looking into this earlier. Your test case indeed hit the perfect edge case. With only value, the delta bit-packing encoder had no other values to form deltas with, so the code assumed that nothing was there to flush. I prepared a PR which is attached to this ticket which should hopefully solve the issue, but I'll try to give this a further test drive to check for any compatibility issues.
