### ISSUE TITLE
Write sparse data

### ISSUE THREAD

**Issue by dneralla** [fraugster/parquet-go#3]
I was reading through the writer code a bit and was wondering if there's way  to write sparse data as in a more optimized way.  I am working with a huge schema but the  data rows themselves are super sparse (meaning each row only gas data for 5 % of columns in the schema.)
I was using Arrow c++ library  (which is more or less implemented in similar fashion) and profiled using perf and figured 40% of my cpu went in writing nils. 

So here's what I am looking for in some pseudoCode and wanna know if this library supports anything of this kind 

From my understanding here is how current parquet writer implementation works for writing nils is in the fraugster library (I might be wrong)

```
    var data []map[string]interface
    for _, row : = range data {
        for _ , prop := range schema.properties {
             if data[prop] == nil {
                 writer.columnStore.WriteNil()
             }
        }
    }
```

That works but consumes a lot of cpu iterating through nil columns. What i am looking for is some thing like below 

```
var m map[prop]int (built from schema which stores when the last non nil is seen for a column) 
for currIdx, row := range data {
     for _, prop := range event.properties { // instead of iterating on all schema columns jus iterate on whats there on event 
        oldIndex := m[prop]
        writer.columnStore.WriteNilRunLegthEncoded(currIdx-oldIdx)  // currIdx - oldIdx is basically how many nils we saw in between
        m[prop] = currIdx        
     }
}
```

**Comment by panamafrancis** [comment]
I'll have a look into this for you

**Comment by panamafrancis** [comment]
Sorry for the very long delay in answering this.

I would say that it is possible to create a new writer that allows you to write all the data for one column for a single rowgroup in one go which would enable the kind of pipelined approach you describe. However I doubt this could be achieved outside of the package, so you would need to fork parquet-go but perhaps if the changes were minimal we could expose (make public) some functions that would allow this new writer to exist in an external package. As it stands i don't see the need on our end as writing parquet files row by row is not the bottleneck (yet), but we would welcome a prototype implementation.
