### ISSUE TITLE
fileReader.nextRow() fails to read all data in columns of type list with null values in list. 

### ISSUE THREAD

**Issue by msbutler** [fraugster/parquet-go#60]
Replicate the bug by running write-low-level and read-low-level on [my fork](https://github.com/msbutler/parquet-go-1/tree/master/examples). I believe the bug occurs in `column.getNextData()` in `schema.go`, but I'll wait to dig into that function until someone confirms this is indeed a bug. 

Consider the schema:
```
message test {
			required int64 id;
			required binary city (STRING);
			required group population (LIST){
				repeated group list {
            		               optional int64 element;
				}
			}
		}`
```
and input data (notice the `nil` value in the second value of the list):
```
l := map[string]interface{}{"list":[]map[string]interface{}{
		{"element":int64(3)},
		{"element":nil},
		{"element":int64(2)}}}

	inputData := []struct {
		ID   int
		City string
		Pops  map[string]interface{}
	}{
		{ID: 1, City: "Berlin", Pops: l},
```
The writer properly writes the parquet file, which I verified using a different parquet reader: 
```
➜  fraugster-parquet-go git:(master) > parquet-tools cat -json output.parquet
{"id":1,"city":"Berlin","population":{"list":[{"element":3},{},{"element":2}]}}
```
However, when nextRow() returns in `read-low-level.go`, the array column is [3], instead of [3,nil,2]. See this screenshot from my goland debugger, or the extra print statements in my `read-low-level.go` implementation:
![image](https://user-images.githubusercontent.com/35438895/145725919-2f63902a-84af-49bd-9340-22757c679e08.png)

**Comment by msbutler** [comment]
Has anyone had a chance to replicate this? If so, I'd be open digging further and opening a PR. I'd really like to add this  package as a vendor to [cockroachdb](https://github.com/cockroachdb/cockroach)!

**Comment by akrennmair** [comment]
Hi @msbutler, thanks for looking into this! I just tried to reproduce this, and it looks like this may be fixed in the `master` branch. Can you check whether this unit test covers the issue correctly? https://github.com/fraugster/parquet-go/commit/17292945e87da73fe609694da7ad820c59e2e5fe

**Comment by akrennmair** [comment]
I'll be releasing a new version shortly, all I need to wait for is another PR to be reviewed and merged.

**Comment by msbutler** [comment]
@akrennmair just rebased to master and it looks like the issue is resolved! The test looks good. Looking forward to the next release!
