### ISSUE TITLE
Feature Request: Support for string in byte array store

### ISSUE THREAD

**Issue by fzerorubigd** [fraugster/parquet-go#93]
By design, the byte array store, is limited to accept only `[]byte` and not string, so if the `map[string]interface{}` contains the string, then the library returns an error indicated that the type is not supported. 

I am trying to read from a JSON file and write into a parquet, Go json library converts all string fields to Go `string` type and there is no easy way (without introducing a structure) to convert it to `[]byte` instead. 

By modifying the `byteArrayStore` and adding the support for converting the `string` to `[]byte` and `[]string` to `[][]byte`, this problem will be fixed. there is a type check already there, and this will not break the backward compatibility as well. 

If you agree, I can implement it. 

This is the function that needs to be modified : https://github.com/fraugster/parquet-go/blob/3f40bf59ff9ad3654655d030eeeed3086297dd68/type_bytearray.go#L361-L379

**Comment by panamafrancis** [comment]
Hey Forud!

Yea that sounds like a good addition, feel free to send an MR. :)

S
